atd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from atd import views

app_name = 'atd'
urlpatterns = [
    path('top/', views.top_page, name='top'),
    path('target/', views.target_list, name='target_list'),
    path('target/upload/', views.modelform_upload, name='target_upload'),
    path('target/reupload/<int:target_id>/', views.modelform_reupload, name='target_reupload'),
    path('target/edit/<int:target_id>/', views.target_edit, name='target_edit'),
    path('scan/setting/<int:target_id>/', views.scan_setting, name='scan_setting'),
    path('scan/setting/update/<int:target_id>/', views.update_setting, name='update_setting'),
    path('scan/exec/<int:target_id>/', views.scan_exec, name='scan_exec'),
    path('scan/detail/<int:target_id>/', views.scan_detail, name='scan_detail'),
    path('report/', views.report, name='report'),
    path('fix/target/<int:target_id>/', views.scan_exec, name='fix_target'),
    path('target/del/<int:target_id>/', views.target_del, name='target_del'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gyoiboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    # Administrator.
    path('admin/', admin.site.urls),

    # Applications.
    path('atd/', include('atd.urls')),
    path('gyoithon/', include('gyoithon.urls')),

    # Authentication.
    path('api-auth/', include('rest_framework.urls')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
]

atd/forms.py
import os
from django import forms
from atd.models import FileUpload, Target, ScanSettingFGSM, ScanSettingCnW, ScanSettingJSMA


class TargetRegistrationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TargetRegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = FileUpload
        fields = ('file_model', 'file_x_train', 'file_y_train', 'file_x_test', 'file_y_test', 'overview', 'author')


class TargetUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TargetUpdateForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    class Meta:
        model = FileUpload
        fields = ('file_model',)


class TargetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

        self.fields['name'].widget.attrs['readonly'] = 'readonly'
        self.fields['x_train'].widget.attrs['readonly'] = 'readonly'
        self.fields['y_train'].widget.attrs['readonly'] = 'readonly'
        self.fields['x_test'].widget.attrs['readonly'] = 'readonly'
        self.fields['y_test'].widget.attrs['readonly'] = 'readonly'
        self.fields['accuracy'].widget.attrs['readonly'] = 'readonly'
        self.fields['registration_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['rank'].widget.attrs['readonly'] = 'readonly'
        self.fields['last_scan_date'].widget.attrs['readonly'] = 'readonly'
        self.fields['status'].widget.attrs['readonly'] = 'readonly'
        self.fields['target_path'].widget.attrs['readonly'] = 'readonly'

    class Meta:
        model = Target
        fields = ('name', 'x_train', 'y_train', 'x_test', 'y_test', 'overview', 'author', 'accuracy',
                  'registration_date', 'rank', 'last_scan_date', 'status', 'target_path')


# FGSM.
class FGSMSettingForm(forms.ModelForm):
    class Meta:
        model = ScanSettingFGSM
        fields = ('epsilon', 'epsilon_step', 'targeted', 'batch_size', 'dataset_num',)


# CnW.
class CnWSettingForm(forms.ModelForm):
    class Meta:
        model = ScanSettingCnW
        fields = ('confidence', 'batch_size', 'dataset_num',)


# JSMA.
class JSMASettingForm(forms.ModelForm):
    class Meta:
        model = ScanSettingJSMA
        fields = ('theta', 'gamma', 'batch_size', 'dataset_num',)

atd/views.py
import os
import shutil

from django.shortcuts import render, get_object_or_404, redirect
from django.http import FileResponse
from django.conf import settings
from django.contrib import messages

from gyoiboard.tasks import executation
from atd.models import Target, ScanResult, ExtScanResult, \
    ExtScanResultEvasion, ScanSettingFGSM, ScanSettingCnW, ScanSettingJSMA, ExtEvasionFGSM, ExtEvasionCnW, ExtEvasionJSMA
from atd.forms import TargetRegistrationForm, TargetUpdateForm, TargetForm, \
    FGSMSettingForm, CnWSettingForm, JSMASettingForm
from atd.util import Utilty


# Upload files.
def modelform_upload(request):
    target = Target()
    if request.method == 'POST':
        upload_file = TargetRegistrationForm(request.POST, request.FILES)
        if upload_file.is_valid():
            # Save file.
            saved_file = upload_file.save()

            # Update Target model.
            target.name = request.FILES['file_model']
            target.x_train = request.FILES['file_x_train']
            target.y_train = request.FILES['file_y_train']
            target.x_test = request.FILES['file_x_test']
            target.y_test = request.FILES['file_y_test']
            target.overview = request.POST['overview']
            target.author = request.POST['author']
            target.registration_date = saved_file.uploaded_at.strftime('%Y-%m-%d %H:%M:%S')
            target.target_path = os.path.dirname(saved_file.file_model.url)
            target.save()
            messages.success(request, 'Upload new model: {}'.format(target.name))
            return redirect('atd:target_list')
    else:
        form = TargetRegistrationForm()
    return render(request, 'atd/modelform_upload.html', {'form': form, 'target': target})


# Upload files.
def modelform_reupload(request, target_id=None):
    if target_id:
        target = get_object_or_404(Target, pk=target_id)
    else:
        return redirect('atd:target_list')

    if request.method == 'POST':
        upload_file = TargetUpdateForm(request.POST, request.FILES)
        if upload_file.is_valid():
            # Save file.
            saved_file = upload_file.save()

            # Move new model and remove old model.
            try:
                # Move new file to target directory.
                print(saved_file.file_model.path + '\n' + '.' + target.target_path)
                shutil.move(saved_file.file_model.path, '.' + target.target_path)
                os.remove(os.path.join('.' + target.target_path, target.name))
            except FileExistsError:
                # Overwrite.
                shutil.move(saved_file.file_model.path, '.' + os.path.join(target.target_path, target.name))
            except Exception as e:
                # Overwrite.
                shutil.move(saved_file.file_model.path, '.' + os.path.join(target.target_path, target.name))
            finally:
                shutil.rmtree(os.path.dirname(saved_file.file_model.path))

            # Update Target model.
            target.name = request.FILES['file_model']
            target.registration_date = saved_file.uploaded_at.strftime('%Y-%m-%d %H:%M:%S')
            target.save()
            messages.success(request, 'Re-Upload new model: {}'.format(target.name))
            return redirect('atd:target_list')
    else:
        form = TargetUpdateForm()
    return render(request, 'atd/modelform_reupload.html', {'form': form, 'target': target})


# Get Dashboard items.
def get_dashboard_items():
    rank_count = {'critical': 0, 'weak': 0, 'normal': 0, 'secure': 0}
    weak_point = {'data_poisoning': 0, 'model_poisoning': 0, 'evasion': 0, 'exfiltration': 0}
    scan_num = {'num': 0, 'latest_date': 'N/A'}

    # Get "Target Num" and "Rank Count".
    targets = Target.objects.all().order_by('id')
    if len(targets) != 0:
        for target in targets:
            if target.status == 'Done':
                # Update "Rank Count".
                if target.rank == 'Critical':
                    rank_count['critical'] += 1
                elif target.rank == 'Weak':
                    rank_count['weak'] += 1
                elif target.rank == 'Normal':
                    rank_count['normal'] += 1
                elif target.rank == 'Secure':
                    rank_count['secure'] += 1

                # Update "Weak Point".
                _, dp_worst_count, mp_worst_count, ev_worst_count, ex_worst_count = get_worst_rank(target.id)
                weak_point['data_poisoning'] += dp_worst_count
                weak_point['model_poisoning'] += mp_worst_count
                weak_point['evasion'] += ev_worst_count
                weak_point['exfiltration'] += ex_worst_count

    # Get "Scan Num".
    results = ScanResult.objects.order_by('id')
    for result in results:
        ext_result = ExtScanResult.objects.db_manager('atd').filter(scan_id__exact=result.scan_id)
        if len(ext_result) == 0:
            continue
        if ext_result[0].status == 'Done':
            scan_num['num'] += 1
            scan_num['latest_date'] = ext_result[0].exec_end_date

    return rank_count, weak_point, scan_num


# Count worst rank.
def count_worst_count(target_id, worst_rank, method_list):
    utility = Utilty()
    worst_count = 0
    for attack_method in method_list:
        result = ExtScanResult.objects.db_manager('atd').filter(target_id__exact=target_id,
                                                                status__exact='Done',
                                                                attack_method__exact=attack_method).reverse().first()
        if result is None:
            continue

        if utility.transform_rank_to_number(result.rank) > worst_rank:
            worst_rank = utility.transform_rank_to_number(result.rank)
        if utility.transform_rank_to_number(result.rank) >= utility.transform_rank_to_number('Weak'):
            worst_count += 1
    return worst_rank, worst_count


# Get worst rank per target.
def get_worst_rank(target_id):
    rank_list = ['Secure', 'Normal', 'Weak', 'Critical']
    worst_rank = 0

    # Data Poisoning.
    worst_rank, dp_worst_count = count_worst_count(target_id, worst_rank, ['feature_collision',
                                                                           'convex_polytope',
                                                                           'bullseye_polytope'])

    # Model Poisoning.
    worst_rank, mp_worst_count = count_worst_count(target_id, worst_rank, ['node_injection',
                                                                           'layer_injection'])

    # Evasion.
    worst_rank, ev_worst_count = count_worst_count(target_id, worst_rank, ['fgsm', 'cnw', 'jsma'])

    # Evasion.
    worst_rank, ex_worst_count = count_worst_count(target_id, worst_rank, ['membership_inference',
                                                                           'label_only',
                                                                           'inversion'])

    return rank_list[worst_rank], dp_worst_count, mp_worst_count, ev_worst_count, ex_worst_count


# Update target's information.
def update_target(targets):
    for target in targets:
        result = ScanResult.objects.filter(scan_result__exact=target.id).order_by('id').reverse().first()
        if result is None:
            continue

        ext_result = ExtScanResult.objects.db_manager('atd').filter(scan_id__exact=result.scan_id)
        if len(ext_result) == 0:
            continue

        # Get worst rank for target.
        worst_rank, _, _, _, _ = get_worst_rank(target.id)
        target.rank = worst_rank

        if ext_result[0].status == 'Done':
            target.accuracy = ext_result[0].accuracy
            target.last_scan_date = ext_result[0].exec_end_date
            target.status = ext_result[0].status
            target.save()

    return targets


# Top Page (Dashboard).
def top_page(request):
    # Get "Target List".
    targets = Target.objects.all().order_by('id')
    targets = update_target(targets)

    rank_count, weak_point, scan_num = get_dashboard_items()
    return render(request, 'atd/index.html', {'rank_count': rank_count,
                                              'weak_point': weak_point,
                                              'scan_num': scan_num,
                                              'targets': targets})


# Target list.
def target_list(request):
    targets = Target.objects.all().order_by('id')
    targets = update_target(targets)
    return render(request, 'atd/target_list.html', {'targets': targets})


# Edit Target's information.
def target_edit(request, target_id=None):
    if target_id:
        target = get_object_or_404(Target, pk=target_id)
    else:
        target = Target()

    if request.method == 'POST':
        form = TargetForm(request.POST, request.FILES, instance=target)
        if form.is_valid():
            target = form.save(commit=False)
            target.save()
            messages.success(request, 'Update target\'s information: {}.{}'.format(target_id, target.name))
            return redirect('atd:target_list')
    else:
        form = TargetForm(instance=target)

    return render(request, 'atd/target_edit.html', dict(target=target, form=form, target_id=target_id))


# Get specify record using target id, attack method.
def select_specify_record(target_id, attack_method):
    scan_result = ScanResult.objects.filter(scan_result__exact=target_id,
                                            attack_method__exact=attack_method).order_by('id').reverse().first()
    if scan_result is None:
        return None
    else:
        return ExtScanResult.objects.db_manager('atd').filter(scan_id__exact=scan_result.scan_id)


# Get all scan results.
def get_scan_results(target_id):
    if target_id:
        target = get_object_or_404(Target, pk=target_id)
    else:
        return redirect('atd:target_list')

atd/templates/atd/index.html
{% extends "atd/base.html" %}

{% block title %}ATD Dashboard{% endblock title %}

{% block breadcrumb_title %}Overview{% endblock breadcrumb_title %}

{% block body_title %}Dashboard{% endblock body_title %}

{% block body_description %}This is the dashboard of ATD{% endblock body_description %}

{% block content %}
<!-- Row 1 -->
<div class="row my-3">
    <!-- Card 1 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <h5 class="card-header">Rank Count</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>Critical</th>
                            <th>Weak</th>
                            <th>Normal</th>
                            <th>Secure</th>
                        </tr>
                        <tr>
                            <td>{{ rank_count.critical }}</td>
                            <td>{{ rank_count.weak }}</td>
                            <td>{{ rank_count.normal }}</td>
                            <td>{{ rank_count.secure }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Card 2 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <h5 class="card-header">Weak Point</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>DP</th>
                            <th>MP</th>
                            <th>EV</th>
                            <th>EX</th>
                        </tr>
                        <tr>
                            <td>{{ weak_point.data_poisoning }}</td>
                            <td>{{ weak_point.model_poisoning }}</td>
                            <td>{{ weak_point.evasion }}</td>
                            <td>{{ weak_point.exfiltration }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Card 3 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <h5 class="card-header">Weakness Changes</h5>
            <div class="card-body">
                <h5 class="card-title">{{ scan_num.num }}</h5>
                <p class="card-text">Latest Scan: {{ scan_num.latest_date }}</p>
                <p class="card-text text-success">4.6% increase since last month</p>
            </div>
        </div>
    </div>
</div>

<!-- Row 2 -->
<div class="row my-3">
    <!-- Card 1 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <div class="card-body">
                <div id="rank-chart"></div>
            </div>
        </div>
    </div>
    <!-- Card 2 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <div class="card-body">
                <div id="weak-chart"></div>
            </div>
        </div>
    </div>
    <!-- Card 3 -->
    <div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
        <div class="card">
            <div class="card-body">
                <div id="traffic-chart3"></div>
            </div>
        </div>
    </div>
</div>

<!-- Row 3 -->
<div class="row">
    <div class="col-12 col-xl-12 mb-4 mb-lg-0">
        <div class="card">
            <h5 class="card-header">Target List</h5>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Model name</th>
                            <th scope="col">Overview</th>
                            <th scope="col">Author</th>
                            <th scope="col">Registration</th>
                            <th scope="col">Rank</th>
                            <th scope="col">Scan date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Operation</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for target in targets %}
                        <tr>
                            <th scope="row">{{ target.id }}</th>
                            <td><a href="{% url 'atd:target_reupload' target_id=target.id %}">{{ target.name }}</a></td>
                            <td>{{ target.overview }}</td>
                            <td>{{ target.author }}</td>
                            <td>{{ target.registration_date}}</td>
                            <td>{{ target.rank }}</td>
                            <td>{{ target.last_scan_date }}</td>
                            <td>{{ target.status }}</td>
                            <td>
                                <a href="{% url 'atd:scan_detail' target_id=target.id %}" class="btn btn-primary btn-sm">View</a>
                                <a href="{% url 'atd:target_edit' target_id=target.id %}" class="btn btn-info btn-sm">Edit</a>
                                <a href="{% url 'atd:target_del' target_id=target.id %}" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <a href="{% url 'atd:target_list' %}" class="btn btn-block btn-light">View all</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
    /* Rank Count */
    let label_critical = 'Critical';
    let label_weak = 'Weak';
    let label_normal = 'Normal';
    let label_secure = 'Secure';
    if ({{ rank_count.critical }} === 0){
        label_critical = ''
    }
    if ({{ rank_count.weak }} === 0){
        label_weak = ''
    }
    if ({{ rank_count.normal }} === 0){
        label_normal = ''
    }
    if ({{ rank_count.secure }} === 0){
        label_secure = ''
    }
    new Chartist.Pie('#rank-chart', {
        series: [{{ rank_count.critical }}, {{ rank_count.weak }}, {{ rank_count.normal }}, {{ rank_count.secure }}],
        labels: [label_critical, label_weak, label_normal, label_secure]
    }, {
        donut: true,
        donutWidth: 40,
        donutSolid: true,
        startAngle: 270
    });

    /* Rank Count */
    let label_dp = 'Data Poisoning';
    let label_mp = 'Model Poisoning';
    let label_evasion = 'Evasion';
    let label_exfiltration = 'Exfiltration';
    if ({{ weak_point.data_poisoning }} === 0){
        label_dp = ''
    }
    if ({{ weak_point.model_poisoning }} === 0){
        label_mp = ''
    }
    if ({{ weak_point.evasion }} === 0){
        label_evasion = ''
    }
    if ({{ weak_point.exfiltration }} === 0){
        label_exfiltration = ''
    }
    new Chartist.Pie('#weak-chart', {
        series: [{{ weak_point.data_poisoning }}, {{ weak_point.model_poisoning }}, {{ weak_point.evasion }}, {{ weak_point.exfiltration }}],
        labels: [label_dp, label_mp, label_evasion, label_exfiltration]
    }, {
        donut: true,
        donutWidth: 40,
        donutSolid: true,
        startAngle: 270
    });

    new Chartist.Line('#traffic-chart3', {
        labels: ['January', 'Februrary', 'March', 'April', 'May', 'June'],
        series: [
            [23000, 25000, 19000, 34000, 56000, 64000]
        ]
    }, {
        low: 0,
        showArea: false
    });
</script>
{% endblock extra_js %}

atd/templates/atd/modelform_upload.html
{% extends "atd/base.html" %}
{% load bootstrap4 %}

{% block title %}Model Upload{% endblock title %}

{% block breadcrumb_title %}Model Upload{% endblock breadcrumb_title %}

{% block body_title %}Model Upload{% endblock body_title %}

{% block body_description %}You can upload a new model and dataset.{% endblock body_description %}

{% block content %}
<form action="{% url 'atd:target_upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
        <div class="form-group row">
            <div class="offset-md-3 col-md-9">
                <button type="submit" class="btn btn-primary">Upload</button>
            </div>
        </div>
</form>
{% endblock content %}

atd/templates/atd/target_edit.html
{% extends "atd/base.html" %}
{% load bootstrap4 %}

{% block title %}Model Edit{% endblock title %}

{% block breadcrumb_title %}Model Edit{% endblock breadcrumb_title %}

{% block body_title %}Model Edit{% endblock body_title %}

{% block body_description %}You can edit model's information.{% endblock body_description %}

{% block content %}
<h4 class="mt-4 border-bottom">{{ target_id }}.{{ target.name }}</h4>

<form action="{% url 'atd:target_edit' target_id=target_id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="form-group row">
        <div class="offset-md-3 col-md-9">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
</form>
<a href="{% url 'atd:target_list' %}" class="btn btn-secondary">Back</a>
{% endblock content %}

atd/templates/atd/target_list.html
{% extends "atd/base.html" %}

{% block title %}Target List{% endblock title %}

{% block breadcrumb_title %}Target List{% endblock breadcrumb_title %}

{% block body_title %}Target List{% endblock body_title %}

{% block body_description %}This is the target list.{% endblock body_description %}

{% block content %}
<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Model name</th>
            <th scope="col">Overview</th>
            <th scope="col">Author</th>
            <th scope="col">Registration</th>
            <th scope="col">Rank</th>
            <th scope="col">Scan date</th>
            <th scope="col">Status</th>
            <th scope="col">Operation</th>
          </tr>
          </thead>
          <tbody>
          {% for target in targets %}
          <tr>
            <th scope="row">{{ target.id }}</th>
            <td><a href="{% url 'atd:target_reupload' target_id=target.id %}">{{ target.name }}</a></td>
            <td>{{ target.overview }}</td>
            <td>{{ target.author }}</td>
            <td>{{ target.registration_date}}</td>
            <td>{{ target.rank }}</td>
            <td>{{ target.last_scan_date }}</td>
            <td>{{ target.status }}</td>
            <td>
              <a href="{% url 'atd:scan_detail' target_id=target.id %}" class="btn btn-info btn-sm">View</a>
              <a href="{% url 'atd:target_edit' target_id=target.id %}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{% url 'atd:target_del' target_id=target.id %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}