atd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from atd import views

app_name = 'atd'
urlpatterns = [
    path('top/', views.top_page, name='top'),
    path('target/', views.target_list, name='target_list'),
    path('target/upload/', views.modelform_upload, name='target_upload'),
    path('target/reupload/<int:target_id>/', views.modelform_reupload, name='target_reupload'),
    path('target/edit/<int:target_id>/', views.target_edit, name='target_edit'),
    path('scan/setting/<int:target_id>/', views.scan_setting, name='scan_setting'),
    path('scan/setting/update/<int:target_id>/', views.update_setting, name='update_setting'),
    path('scan/exec/<int:target_id>/', views.scan_exec, name='scan_exec'),
    path('scan/detail/<int:target_id>/', views.scan_detail, name='scan_detail'),
    path('report/', views.report, name='report'),
    path('fix/target/<int:target_id>/', views.scan_exec, name='fix_target'),
    path('target/del/<int:target_id>/', views.target_del, name='target_del'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gyoiboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    # Administrator.
    path('admin/', admin.site.urls),

    # Applications.
    path('atd/', include('atd.urls')),
    path('gyoithon/', include('gyoithon.urls')),

    # Authentication.
    path('api-auth/', include('rest_framework.urls')),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
]

gyoithon/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

gyoithon/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from gyoithon import views
from gyoithon.views import OrganizationViewSet, OrganizationDetailSet, OrganizationCreateSet, OrganizationUpdateSet, \
    DomainViewSet, DomainDetailSet, DomainCreateSet, DomainUpdateSet, SubdomainViewSet, SubdomainDetailSet, \
    SubdomainCreateSet, SubdomainUpdateSet, AssessmentViewSetOrganization, AssessmentViewSetDomain,\
    AssessmentViewSetSubdomain, AssessmentDetailSet, AssessmentUpdateSet

# Application.
app_name = 'gyoithon'

# REST API.
apipatterns = [
    path('api/organization/', OrganizationViewSet.as_view()),
    path('api/organization/<int:pk>/', OrganizationDetailSet.as_view()),
    path('api/organization/add/', OrganizationCreateSet.as_view()),
    path('api/organization/edit/<int:pk>/', OrganizationUpdateSet.as_view()),
    path('api/domain/<int:pk>/', DomainDetailSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/', DomainViewSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/add/', DomainCreateSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/edit/<int:pk>/', DomainUpdateSet.as_view()),
    path('api/subdomain/<int:pk>/', SubdomainDetailSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/<int:related_domain_id>/subdomain/', SubdomainViewSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/<int:related_domain_id>/subdomain/add/', SubdomainCreateSet.as_view()),
    path('api/organization/<int:related_organization_id>/domain/<int:related_domain_id>/subdomain/edit/<int:pk>/', SubdomainUpdateSet.as_view()),
    path('api/assessment/<int:pk>/', AssessmentDetailSet.as_view()),
    path('api/organization/<int:related_organization_id>/assessment/', AssessmentViewSetOrganization.as_view()),
    path('api/domain/<int:related_domain_id>/assessment/', AssessmentViewSetDomain.as_view()),
    path('api/subdomain/<int:related_subdomain_id>/assessment/', AssessmentViewSetSubdomain.as_view()),
    path('api/assessment/edit/<int:pk>/', AssessmentUpdateSet.as_view()),
]

urlpatterns = [
    path('top/', views.top_page, name='top_page'),
    path('organization/add', views.registration, name='registration'),
    path('organization/list', views.list_organization, name='list_organization'),
    path('organization/<int:organization_id>/edit', views.edit_organization, name='edit_organization'),
    path('organization/<int:organization_id>/del', views.delete_organization, name='delete_organization'),
    path('organization/<int:organization_id>/', views.detail_organization, name='detail_organization'),
    path('organization/<int:organization_id>/domain/add', views.registration_domain, name='registration_domain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/edit', views.edit_domain, name='edit_domain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/del', views.delete_domain, name='delete_domain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/', views.detail_domain, name='detail_domain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/subdomain/add', views.registration_subdomain, name='registration_subdomain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/subdomain/<int:subdomain_id>/edit', views.edit_subdomain, name='edit_subdomain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/subdomain/<int:subdomain_id>/del', views.delete_subdomain, name='delete_subdomain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/subdomain/<int:subdomain_id>/', views.detail_subdomain, name='detail_subdomain'),
    path('organization/<int:organization_id>/search/domain', views.search_domain, name='search_domain'),
    path('organization/<int:organization_id>/domain/<int:domain_id>/search/subdomain/', views.search_subdomain, name='search_subdomain'),
]

# Add API patterns.
urlpatterns.extend(apipatterns)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gyoithon/models.py
from django.db import models
from django.utils import timezone


# Enum of REGION.
class REGION(models.IntegerChoices):
    NONE_SELECT = 0, '-----'
    DOMESTIC = 1, 'Domestic'
    ABROAD = 2, 'Abroad'


# Enum of INDUSTRY.
class INDUSTRY(models.IntegerChoices):
    NONE_SELECT = 0, '-----'
    ENERGY = 1, 'Energy'
    MATERIALS = 2, 'Materials'
    INDUSTRIALS = 3, 'Industrials'
    CONSUMER_DISCRETIONARY = 4, 'Consumer Discretionary'
    CONSUMER_STAPLES = 5, 'Consumer Staples'
    HEALTH_CARE = 6, 'Health Care'
    FINANCIALS = 7, 'Financials'
    INFORMATION_TECHNOLOGY = 8, 'Information Technology'
    COMMUNICATION_SERVICES = 9, 'Communication Services'
    UTILITIES = 10, 'Utilities'
    REAL_ESTATE = 11, 'Real Estate'


# Enum of Cloud Type.
class CLOUDTYPE(models.IntegerChoices):
    NONE_SELECT = 0, '-----'
    AWS = 1, 'Amazon Web Service'
    GCP = 2, 'Google Cloud Platform'
    AZURE = 3, 'Microsoft Azure'


# Enum of Production.
class PRODUCTION(models.IntegerChoices):
    NONE_SELECT = 0, '-----'
    DEVELOPMENT = 1, 'Development'
    LAUNCHED = 2, 'Production'


# Enum of Rank.
class RANK(models.IntegerChoices):
    NONE_SELECT = 0, '-----'
    SECURE = 1, 'Secure'
    NORMAL = 2, 'Normal'
    WEAK = 3, 'Weak'
    CRITICAL = 4, 'Critical'


# Enum of Status.
class STATUS(models.IntegerChoices):
    STOP = 0, '-----'
    SEARCH = 1, 'Search'
    ASSESS = 2, 'Assess'


# Organization.
class Organization(models.Model):
    name = models.CharField(verbose_name='Organization Name', max_length=255, blank=False)
    region = models.IntegerField(verbose_name='Region', choices=REGION.choices, default=0)
    industry = models.IntegerField(verbose_name='Industry', choices=INDUSTRY.choices, default=0)
    overview = models.TextField(verbose_name='Overview', max_length=1000, default='N/A')
    domain = models.IntegerField(verbose_name='Domain', default=0)
    subdomain = models.IntegerField(verbose_name='Subdomain', default=0)
    rank = models.IntegerField(verbose_name='Rank', choices=RANK.choices, default=0)
    status = models.IntegerField(verbose_name='Status', choices=STATUS.choices, default=0)
    invisible = models.BooleanField(verbose_name='Invisible', default=False)
    registration_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name


# Domain.
class Domain(models.Model):
    related_organization_id = models.IntegerField(verbose_name='Related Organization ID', blank=False)
    name = models.CharField(verbose_name='Domain Name', max_length=255, blank=False)
    overview = models.TextField(verbose_name='Overview', max_length=1000, default='N/A')
    registrar = models.CharField(verbose_name='Registrar', max_length=255, default='N/A')
    administrative_contact = models.CharField(verbose_name='Administrative Contact', max_length=255, default='N/A')
    registrant_name = models.CharField(verbose_name='Registrant Name', max_length=255, default='N/A')
    registrant_organization = models.CharField(verbose_name='Registrant Organization', max_length=255, default='N/A')
    registrant_email = models.CharField(verbose_name='Registrant Email', max_length=255, default='N/A')
    admin_name = models.CharField(verbose_name='Admin Name', max_length=255, default='N/A')
    admin_organization = models.CharField(verbose_name='Admin Organization', max_length=255, default='N/A')
    admin_email = models.CharField(verbose_name='Admin Email', max_length=255, default='N/A')
    tech_name = models.CharField(verbose_name='Tech Name', max_length=255, default='N/A')
    tech_organization = models.CharField(verbose_name='Tech Organization', max_length=255, default='N/A')
    tech_email = models.CharField(verbose_name='Tech Email', max_length=255, default='N/A')
    name_server = models.TextField(verbose_name='Name Server', max_length=1000, default='N/A')
    subdomain = models.IntegerField(verbose_name='Subdomain', default=0)
    rank = models.IntegerField(verbose_name='Rank', choices=RANK.choices, default=0)
    status = models.IntegerField(verbose_name='Status', choices=STATUS.choices, default=0)
    invisible = models.BooleanField(verbose_name='Invisible', default=False)
    registration_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name


# Subdomain.
class Subdomain(models.Model):
    related_organization_id = models.IntegerField(verbose_name='Related Organization ID', blank=False)
    related_domain_id = models.IntegerField(verbose_name='Related Domain ID', blank=False)
    name = models.CharField(verbose_name='Subdomain Name', max_length=255, blank=False)
    overview = models.TextField(verbose_name='Overview', max_length=1000, default='N/A')
    ip_address = models.TextField(verbose_name='IP Address', max_length=255, default='N/A')
    production = models.IntegerField(verbose_name='Production Environment', choices=PRODUCTION.choices, default=0)
    url_origin = models.CharField(verbose_name='Top URL', max_length=255, default='N/A')
    cloud_type = models.IntegerField(verbose_name='Cloud Type', choices=CLOUDTYPE.choices, default=0)
    auth_form = models.BooleanField(verbose_name='Form Authentication', default=False)
    auth_basic = models.BooleanField(verbose_name='Basic Authentication', default=False)
    http_accessible = models.CharField(verbose_name='Accessible (HTTP)', max_length=255, default='N/A')
    http_location = models.CharField(verbose_name='Location (HTTP)', max_length=1000, default='N/A')
    http_page_title = models.CharField(verbose_name='Page Title (HTTP)', max_length=1000, default='N/A')
    http_screenshot_url = models.CharField(verbose_name='Screenshot Captured URL (HTTP)', max_length=1000, default='N/A')
    http_screenshot_path = models.CharField(verbose_name='Path to save the Screenshot (HTTP)', max_length=1000, default='N/A')
    https_accessible = models.CharField(verbose_name='Accessible (HTTPS)', max_length=255, default='N/A')
    https_location = models.CharField(verbose_name='Location (HTTPS)', max_length=1000, default='N/A')
    https_page_title = models.CharField(verbose_name='Page Title (HTTPS)', max_length=1000, default='N/A')
    https_screenshot_url = models.CharField(verbose_name='Screenshot Captured URL (HTTPS)', max_length=1000, default='N/A')
    https_screenshot_path = models.CharField(verbose_name='Path to save the Screenshot (HTTPS)', max_length=1000, default='N/A')
    dns_a_record = models.TextField(verbose_name='DNS A Record', max_length=5000, default='N/A')
    dns_cname_record = models.TextField(verbose_name='DNS CNAME Record', max_length=5000, default='N/A')
    dns_ns_record = models.TextField(verbose_name='DNS NS Record', max_length=5000, default='N/A')
    dns_mx_record = models.TextField(verbose_name='DNS MX Record', max_length=5000, default='N/A')
    dns_soa_record = models.TextField(verbose_name='DNS SOA Record', max_length=5000, default='N/A')
    dns_txt_record = models.TextField(verbose_name='DNS TXT Record', max_length=5000, default='N/A')
    rank = models.IntegerField(verbose_name='Rank', choices=RANK.choices, default=0)
    status = models.IntegerField(verbose_name='Status', choices=STATUS.choices, default=0)
    invisible = models.BooleanField(verbose_name='Invisible', default=False)
    registration_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name


# Assessment.
class Assessment(models.Model):
    related_organization_id = models.IntegerField(verbose_name='Related Organization ID', blank=False)
    related_domain_id = models.IntegerField(verbose_name='Related Domain ID', blank=False)
    related_subdomain_id = models.IntegerField(verbose_name='Related Subdomain ID', blank=False)
    scan_date = models.DateTimeField(default=timezone.now())
    target_port = models.IntegerField(verbose_name='Port', default=80, blank=False)
    assessment_url = models.CharField(verbose_name='Assessment URL', max_length=255, default='N/A')
    http_status = models.CharField(verbose_name='HTTP Status', max_length=3, default='N/A')
    product_vendor = models.CharField(verbose_name='Product Vendor', max_length=255, default='N/A')
    product_name = models.CharField(verbose_name='Product Name', max_length=255, default='N/A')
    product_version = models.CharField(verbose_name='Product Version', max_length=255, default='N/A')
    product_type = models.CharField(verbose_name='Product Type', max_length=255, default='N/A')
    product_trigger = models.CharField(verbose_name='Product Trigger', max_length=5000, default='N/A')
    product_cveid = models.CharField(verbose_name='CVE-ID', max_length=255, default='N/A')
    auth_form_trigger_ml = models.CharField(verbose_name='ML Trigger of Form Auth', max_length=5000, default='N/A')
    auth_form_trigger_url = models.CharField(verbose_name='URL Trigger of Form Auth', max_length=5000, default='N/A')
    auth_basic_trigger = models.CharField(verbose_name='Trigger of BASIC Auth', max_length=5000, default='N/A')
    unnecessary_comments = models.CharField(verbose_name='Unnecessary Comments', max_length=5000, default='N/A')
    unnecessary_contents = models.CharField(verbose_name='Unnecessary Contents', max_length=5000, default='N/A')
    directory_index = models.CharField(verbose_name='Directory Index', max_length=5000, default='N/A')
    error_messages = models.CharField(verbose_name='Error Messages', max_length=5000, default='N/A')
    server_header = models.CharField(verbose_name='Server Header', max_length=5000, default='N/A')
    log_path = models.CharField(verbose_name='Log', max_length=1000, default='N/A')
    note = models.CharField(verbose_name='Note', max_length=5000, default='N/A')
    invisible = models.BooleanField(verbose_name='Invisible', default=False)

    def __str__(self):
        return self.related_subdomain_id

gyoithon/mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

gyoithon/templates/gyoithon/detail_organization.html
{% extends "gyoithon/base.html" %}

{% block title %}{{ organization.name }}{% endblock title %}

{% block breadcrumb_title %}{{ organization.name }}{% endblock breadcrumb_title %}

{% block body_title %}{{ organization.name }}{% endblock body_title %}

{% block body_description %}{{ organization.overview | linebreaksbr }}{% endblock body_description %}

{% block content %}
<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Registration Date</th>
            <td>{{ organization.registration_date }}</td>
          </tr>
          <tr>
            <th>Region</th>
            <td>{{ organization.get_region_display }}</td>
          </tr>
          <tr>
            <th>Industry</th>
            <td>{{ organization.get_industry_display }}</td>
          </tr>
          <tr>
            <th>Domains</th>
            <td>{{ organization.domain }}</td>
          </tr>
          <tr>
            <th>Subdomains</th>
            <td>{{ organization.subdomain }}</td>
          </tr>
          <tr>
            <th>Rank</th>
            <td>{{ organization.get_rank_display }}</td>
          </tr>
          <tr>
            <th>Status</th>
            <td>{{ organization.get_status_display }}</td>
          </tr>
          <tr>
            <th colspan="2">
              <a href="{% url 'gyoithon:edit_organization' organization_id=organization.id %}" class="btn btn-info">Edit</a>
              <a href="{% url 'gyoithon:search_domain' organization_id=organization.id %}" class="btn btn-success">Search Domain</a>
              <a href="{% url 'gyoithon:registration_domain' organization_id=organization.id %}" class="btn btn-info">Add Domain</a>
            </th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

<h4 class="mt-4 border-bottom">Domain List</h4>
<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>No</th>
            <th>Name</th>
            <th>Registration Date</th>
            <th>Registrant Organization</th>
            <th>Registrant Email</th>
            <th>Subdomains</th>
            <th>Rank</th>
            <th>Status</th>
            <th colspan="2"></th>
          </tr>
          </thead>
          {% for domain in domains %}
          {% if domain.invisible == 0 %}
          <tr>
            <th scope="row">{{ domain.id }}</th>
            <td>{{ domain.name }}</td>
            <td>{{ domain.registration_date}}</td>
            <td>{{ domain.registrant_organization }}</td>
            <td>{{ domain.registrant_email }}</td>
            <td>{{ domain.subdomain }}</td>
            <td>{{ domain.get_rank_display }}</td>
            <td>{{ domain.get_status_display }}</td>
            <td>
              <input type="checkbox" name="bulk_vulnerability_assessment" value="1">
            </td>
            <td>
              <a href="{% url 'gyoithon:detail_domain' organization_id=organization.id domain_id=domain.id %}" class="btn btn-primary btn-sm">View</a>
              <a href="{% url 'gyoithon:edit_domain' organization_id=organization.id domain_id=domain.id %}" class="btn btn-info btn-sm">Edit</a>
              <a href="{% url 'gyoithon:delete_domain' organization_id=organization.id domain_id=domain.id %}" class="btn btn-danger btn-sm">Hide</a>
            </td>
          </tr>
          {% endif %}
          {% endfor %}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td colspan="5">
              <button type="submit" class="btn btn-success">Search Subdomain</button>
              <button type="submit" class="btn btn-warning">Assess</button>
              <button type="submit" class="btn btn-dark">Search & Assess</button>
              <button type="submit" class="btn btn-secondary">Hidden Domain</button>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<a href="{% url 'gyoithon:list_organization' %}" class="btn btn-secondary">Back</a>
{% endblock content %}

gyoithon/templates/gyoithon/detail_subdomain.html
{% extends "gyoithon/base.html" %}
{% load i18n static %}

{% block title %}{{ subdomain.name }}{% endblock title %}

{% block breadcrumb_title %}
<a href="{% url 'gyoithon:detail_organization' organization_id=organization.id %}">{{ organization.name }}</a>
&nbsp;/&nbsp;
<a href="{% url 'gyoithon:detail_domain' organization_id=organization.id domain_id=domain.id %}">{{ domain.name }}</a>
&nbsp;/&nbsp;
{{ subdomain.name }}
{% endblock breadcrumb_title %}

{% block body_title %}{{ subdomain.name }}{% endblock body_title %}

{% block body_description %}{{ subdomain.overview | linebreaksbr }}{% endblock body_description %}

{% block content %}
{% if subdomain.http_screenshot_url != 'N/A' %}
<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th><a href="{{ subdomain.http_screenshot_url }}">{{ subdomain.http_screenshot_url }}</a></th>
            <th><a href="{{ subdomain.https_screenshot_url }}">{{ subdomain.https_screenshot_url }}</a></th>
          </tr>
          </thead>
          <tr>
            <td>
              <figure>
                <img src="{% static 'gyoithon/img/screenshot/' %}{{ subdomain.http_screenshot_path }}" alt="{{ subdomain.http_page_title }}" width="50%">
                <figcaption>{{ subdomain.http_page_title }}</figcaption>
              </figure>
            </td>
            <td>
              <figure>
                <img src="{% static 'gyoithon/img/screenshot/' %}{{ subdomain.https_screenshot_path }}" alt="{{ subdomain.https_page_title }}" width="50%">
                <figcaption>{{ subdomain.https_page_title }}</figcaption>
              </figure>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Registration Date</th>
            <td>{{ subdomain.registration_date }}</td>
          </tr>
          <tr>
            <th>IP Address</th>
            <td>{{ subdomain.ip_address | linebreaksbr }}</td>
          </tr>
          <tr>
            <th>Environment</th>
            <td>{{ subdomain.get_production_display }}</td>
          </tr>
          <tr>
            <th>Cloud Type</th>
            <td>{{ subdomain.get_cloud_type_display }}</td>
          </tr>
          <tr>
            <th>HTTP Accessible</th>
            <td>{{ subdomain.http_accessible }}&nbsp;(&nbsp;{{ subdomain.http_location }}&nbsp;)</td>
          </tr>
          <tr>
            <th>HTTPS Accessible</th>
            <td>{{ subdomain.https_accessible }}&nbsp;(&nbsp;{{ subdomain.https_location }}&nbsp;)</td>
          </tr>
          <tr>
            <th>DNS Record</th>
            <td>{{ subdomain.dns_a_record | linebreaksbr }}</td>
          </tr>
          <tr>
            <th>Rank</th>
            <td>{{ subdomain.get_rank_display }}</td>
          </tr>
          <tr>
            <th>Status</th>
            <td>{{ subdomain.get_status_display }}</td>
          </tr>
          <tr>
            <th colspan="2">
              <a href="{% url 'gyoithon:edit_subdomain' organization_id=organization.id domain_id=domain.id subdomain_id=subdomain.id %}" class="btn btn-info">Edit</a>
              <a href="{% url 'gyoithon:registration_subdomain' organization_id=organization.id domain_id=domain.id %}" class="btn btn-warning">Assess</a>
              <a href="{% url 'gyoithon:delete_subdomain' organization_id=organization.id domain_id=domain.id subdomain_id=subdomain.id %}" class="btn btn-danger">Hide</a>
            </th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

<h4 class="mt-4 border-bottom">Assessment Results</h4>
<div class="col-12 col-xl-12 mb-4 mb-lg-0">
  <div class="card">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>IP Address</th>
            <th>HTTP Accessible</th>
            <th>HTTPS Accessible</th>
            <th>Status</th>
            <th>Registration Date</th>
            <th colspan="2">Operation</th>
          </tr>
          </thead>
          {% for subdomain in subdomains %}
          <tr>
            <th scope="row">{{ subdomain.id }}</th>
            <td>{{ subdomain.name }}</td>
            <td>{{ subdomain.ip_address }}</td>
            <td>{{ subdomain.http_accessible }}</td>
            <td>{{ subdomain.https_accessible }}</td>
            <td>{{ subdomain.status }}</td>
            <td>{{ subdomain.registration_date}}</td>
            <td>
              <input type="checkbox" name="bulk_vulnerability_assessment" value="1">
            </td>
            <td>
              <a href="{% url 'gyoithon:detail_subdomain' organization_id=organization.id domain_id=domain.id subdomain_id=subdomain.id %}" class="btn btn-info btn-sm">View</a>
              <a href="{% url 'gyoithon:edit_subdomain' organization_id=organization.id domain_id=domain.id subdomain_id=subdomain.id %}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{% url 'gyoithon:delete_subdomain' organization_id=organization.id domain_id=domain.id subdomain_id=subdomain.id %}" class="btn btn-danger btn-sm">Hide</a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<a href="{% url 'gyoithon:detail_domain' organization_id=organization.id domain_id=domain.id %}" class="btn btn-secondary">Back</a>
{% endblock content %}

gyoithon/templates/gyoithon/scan_exec.html
{% extends "atd/base.html" %}
{% load bootstrap4 %}

{% block title %}Scan Result{% endblock title %}

{% block content %}
<h4 class="mt-4 mb-5 border-bottom">Scan Result</h4>
{{ result }}

<hr>
<a href="{% url 'atd:target_list' %}" class="btn btn-secondary btn-sm">Back</a>
{% endblock content %}